[package]
name = "polyfund"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "21.0.1-preview.3" }
wee_alloc = "0.4"

[profile.release]
panic = "abort"
lto = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }